/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author seveshy
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setToolTipText("Cadastro de clientes");
        setLayout(null);

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Cadastrar");
        add(jButton1);
        jButton1.setBounds(210, 350, 280, 50);

        name.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        name.setText("Nome");
        add(name);
        name.setBounds(210, 70, 280, 50);

        mail.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        mail.setText("E-mail");
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        add(mail);
        mail.setBounds(210, 130, 280, 50);

        password.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        password.setText("Senha");
        add(password);
        password.setBounds(210, 200, 280, 50);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Realizar cadastro");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 30));
        add(jLabel1);
        jLabel1.setBounds(240, 20, 220, 40);

        jRadioButton1.setText("Masculino");
        add(jRadioButton1);
        jRadioButton1.setBounds(210, 260, 96, 23);

        jRadioButton2.setText("Feminino");
        add(jRadioButton2);
        jRadioButton2.setBounds(210, 290, 89, 23);

        jRadioButton3.setText("Prefiro não informar");
        add(jRadioButton3);
        jRadioButton3.setBounds(210, 320, 190, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
